from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from utils.recommendation_engine import generate_recommendation


def generate_financial_report(user):

    income = float(user[5])
    risk = str(user[6])
    expenses = float(user[7])
    savings = float(user[8])
    goal = str(user[9])
    experience = str(user[10])

    recommendation = generate_recommendation(
        income=income,
        expenses=expenses,
        savings=savings,
        risk=risk,
        goal=goal,
        experience=experience
    )

    financial_score = min(
        100,
        int((savings / income) * 100)
    ) if income else 0

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    elements = []

    # -------------------------------------------------

    elements.append(
        Paragraph(
            "FutureFund AI",
            styles["Title"]
        )
    )

    elements.append(
        Paragraph(
            "Professional Financial Report",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            datetime.now().strftime("%d %B %Y"),
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 20))

    # -------------------------------------------------

    profile = [
        ["Name", user[1]],
        ["Email", user[2]],
        ["Age", str(user[4])],
        ["Monthly Income", f"₹{income:,.0f}"],
        ["Monthly Savings", f"₹{savings:,.0f}"],
        ["Risk Appetite", risk],
        ["Financial Goal", goal],
        ["Experience", experience],
    ]

    table = Table(profile, colWidths=[170, 250])

    table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    elements.append(table)

    elements.append(Spacer(1, 20))

    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Financial Health Score</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            f"Score: {financial_score}/100",
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 18))

    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Recommended Monthly SIP</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            f"₹{recommendation['sip']:,}",
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 18))

    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Portfolio Allocation</b>",
            styles["Heading2"]
        )
    )

    portfolio_data = [["Asset", "Allocation"]]

    for asset, value in recommendation["portfolio"].items():
        portfolio_data.append(
            [asset, f"{value}%"]
        )

    portfolio_table = Table(portfolio_data)

    portfolio_table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
            ("ALIGN", (1, 1), (-1, -1), "CENTER"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    elements.append(portfolio_table)

    elements.append(Spacer(1, 20))

    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Investment Strategy</b>",
            styles["Heading2"]
        )
    )

    for item in recommendation["strategy"]:
        elements.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    elements.append(Spacer(1, 20))

    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Improvement Suggestions</b>",
            styles["Heading2"]
        )
    )

    for item in recommendation["improvements"]:
        elements.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    elements.append(Spacer(1, 30))

    # -------------------------------------------------

    elements.append(
        Paragraph(
            "Generated by FutureFund AI",
            styles["Italic"]
        )
    )

    doc.build(elements)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf